---
- name: Delete F5 API VIP
  f5networks.f5_modules.bigip_virtual_server:
    provider: "{{ provider }}"
    name: "{{ api_vip.vip_name }}"
    state: absent
  ignore_errors: true
  delegate_to: localhost

- name: Delete F5 APP HTTPS VIP
  f5networks.f5_modules.bigip_virtual_server:
    provider: "{{ provider }}"
    name: "{{ app_vip.vip_name }}-https"
    state: absent
  ignore_errors: true
  delegate_to: localhost

- name: Delete F5 APP HTTP VIP
  f5networks.f5_modules.bigip_virtual_server:
    provider: "{{ provider }}"
    name: "{{ app_vip.vip_name }}-http"
    state: absent
  ignore_errors: true
  delegate_to: localhost

- name: Delete API Pool
  f5networks.f5_modules.bigip_pool:
    provider: "{{ provider }}"
    name: "{{ api_vip.pool_name }}"
    lb_method: round-robin
    monitors: /Common/tcp
    monitor_type: and_list
    state: absent
  ignore_errors: true
  delegate_to: localhost

- name: Delete APP HTTPS Pool
  f5networks.f5_modules.bigip_pool:
    provider: "{{ provider }}"
    name: "{{ app_vip.pool_name }}-https"
    lb_method: round-robin
    monitors: /Common/tcp
    monitor_type: and_list
    state: absent
  ignore_errors: true
  delegate_to: localhost

- name: Delete APP HTTP Pool
  f5networks.f5_modules.bigip_pool:
    provider: "{{ provider }}"
    name: "{{ app_vip.pool_name }}-http"
    lb_method: round-robin
    monitors: /Common/tcp
    monitor_type: and_list
    state: absent
  ignore_errors: true
  delegate_to: localhost

- name: Delete API Nodes from F5
  f5networks.f5_modules.bigip_node:
    provider: "{{ provider }}"
    name: "{{ item.key }}"
    state: absent
  delegate_to: localhost
  with_dict: "{{ api_vip.nodes }}"

- name: Delete APP Nodes from F5
  f5networks.f5_modules.bigip_node:
    provider: "{{ provider }}"
    name: "{{ item.key }}"
    state: absent
  delegate_to: localhost
  with_dict: "{{ app_vip.nodes }}"

- name: End playbook
  ansible.builtin.meta: end_play
