- name: Run all the pre-install steps
  ansible.builtin.include_tasks: pre_install.yml

- name: Configure F5 Load Balancer
  ansible.builtin.include_tasks: configure_f5.yml
  when: f5.enabled | default(false) | bool

- name: Run all the install steps
  ansible.builtin.include_tasks: install.yml
